//
//Copyright 2021 Acacio Cruz acacio@acacio.coom
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.33.1
// source: tokens.proto

package secrets

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Secret struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Secret) Reset() {
	*x = Secret{}
	mi := &file_tokens_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Secret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Secret) ProtoMessage() {}

func (x *Secret) ProtoReflect() protoreflect.Message {
	mi := &file_tokens_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Secret.ProtoReflect.Descriptor instead.
func (*Secret) Descriptor() ([]byte, []int) {
	return file_tokens_proto_rawDescGZIP(), []int{0}
}

func (x *Secret) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Secret) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Secret) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type TOTPSecrets struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secrets       []*Secret              `protobuf:"bytes,1,rep,name=secrets,proto3" json:"secrets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TOTPSecrets) Reset() {
	*x = TOTPSecrets{}
	mi := &file_tokens_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TOTPSecrets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TOTPSecrets) ProtoMessage() {}

func (x *TOTPSecrets) ProtoReflect() protoreflect.Message {
	mi := &file_tokens_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TOTPSecrets.ProtoReflect.Descriptor instead.
func (*TOTPSecrets) Descriptor() ([]byte, []int) {
	return file_tokens_proto_rawDescGZIP(), []int{1}
}

func (x *TOTPSecrets) GetSecrets() []*Secret {
	if x != nil {
		return x.Secrets
	}
	return nil
}

var File_tokens_proto protoreflect.FileDescriptor

const file_tokens_proto_rawDesc = "" +
	"\n" +
	"\ftokens.proto\x12\asecrets\"D\n" +
	"\x06Secret\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\"8\n" +
	"\vTOTPSecrets\x12)\n" +
	"\asecrets\x18\x01 \x03(\v2\x0f.secrets.SecretR\asecretsB\vZ\t.;secretsb\x06proto3"

var (
	file_tokens_proto_rawDescOnce sync.Once
	file_tokens_proto_rawDescData []byte
)

func file_tokens_proto_rawDescGZIP() []byte {
	file_tokens_proto_rawDescOnce.Do(func() {
		file_tokens_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tokens_proto_rawDesc), len(file_tokens_proto_rawDesc)))
	})
	return file_tokens_proto_rawDescData
}

var file_tokens_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_tokens_proto_goTypes = []any{
	(*Secret)(nil),      // 0: secrets.Secret
	(*TOTPSecrets)(nil), // 1: secrets.TOTPSecrets
}
var file_tokens_proto_depIdxs = []int32{
	0, // 0: secrets.TOTPSecrets.secrets:type_name -> secrets.Secret
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_tokens_proto_init() }
func file_tokens_proto_init() {
	if File_tokens_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tokens_proto_rawDesc), len(file_tokens_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tokens_proto_goTypes,
		DependencyIndexes: file_tokens_proto_depIdxs,
		MessageInfos:      file_tokens_proto_msgTypes,
	}.Build()
	File_tokens_proto = out.File
	file_tokens_proto_goTypes = nil
	file_tokens_proto_depIdxs = nil
}
