// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tokens.proto

/*
Package secrets is a generated protocol buffer package.

It is generated from these files:
	tokens.proto

It has these top-level messages:
	Secret
	TOTPSecrets
*/
package secrets

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Secret struct {
	Domain string `protobuf:"bytes,1,opt,name=domain" json:"domain,omitempty"`
	Key    string `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
}

func (m *Secret) Reset()                    { *m = Secret{} }
func (m *Secret) String() string            { return proto.CompactTextString(m) }
func (*Secret) ProtoMessage()               {}
func (*Secret) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Secret) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *Secret) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type TOTPSecrets struct {
	Secrets []*Secret `protobuf:"bytes,1,rep,name=secrets" json:"secrets,omitempty"`
}

func (m *TOTPSecrets) Reset()                    { *m = TOTPSecrets{} }
func (m *TOTPSecrets) String() string            { return proto.CompactTextString(m) }
func (*TOTPSecrets) ProtoMessage()               {}
func (*TOTPSecrets) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TOTPSecrets) GetSecrets() []*Secret {
	if m != nil {
		return m.Secrets
	}
	return nil
}

func init() {
	proto.RegisterType((*Secret)(nil), "secrets.Secret")
	proto.RegisterType((*TOTPSecrets)(nil), "secrets.TOTPSecrets")
}

func init() { proto.RegisterFile("tokens.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 123 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0xc9, 0xcf, 0x4e,
	0xcd, 0x2b, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2f, 0x4e, 0x4d, 0x2e, 0x4a, 0x2d,
	0x29, 0x56, 0x32, 0xe2, 0x62, 0x0b, 0x06, 0x33, 0x85, 0xc4, 0xb8, 0xd8, 0x52, 0xf2, 0x73, 0x13,
	0x33, 0xf3, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xa0, 0x3c, 0x21, 0x01, 0x2e, 0xe6, 0xec,
	0xd4, 0x4a, 0x09, 0x26, 0xb0, 0x20, 0x88, 0xa9, 0x64, 0xc1, 0xc5, 0x1d, 0xe2, 0x1f, 0x12, 0x00,
	0xd1, 0x57, 0x2c, 0xa4, 0xc9, 0x05, 0x33, 0x4d, 0x82, 0x51, 0x81, 0x59, 0x83, 0xdb, 0x88, 0x5f,
	0x0f, 0xca, 0xd7, 0x83, 0x28, 0x09, 0x82, 0xc9, 0x27, 0xb1, 0x81, 0x6d, 0x37, 0x06, 0x04, 0x00,
	0x00, 0xff, 0xff, 0xe9, 0x12, 0xe3, 0x35, 0x8d, 0x00, 0x00, 0x00,
}
